#!/bin/sh

mount -a
mkdir -p /dev/shm
mkdir -p /dev/pts
mount devpts

echo /sbin/mdev > /proc/sys/kernel/hotplug

/sbin/mdev -s

/sbin/sysctl -p

telnetd -l sh
mkdir -p /dev/pts
mount -t sysfs none /sys
mount -t tmpfs mdev /dev
mount -t debugfs none /sys/kernel/debug/
mkdir -p /var/lock
mdev -s
mount -t squashfs /dev/mtdblock3 /config
 mount -t jffs2 mtd:customer /customer

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
busybox telnetd&
