#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export LD_LIBRARY_PATH=/lib
mkdir -p /dev/pts
ulimit -c unlimited
export PATH=$PATH:/config
export PATH=$PATH:/usr/bin:/usr/sbin:/customer/bin
export TERMINFO=/config/terminfo
